services:
  nginx:
    build:
      context: ./nginx
      target: dev
    container_name: 'nginx'
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    environment:
      - PROM_USER=${USER_NAME}
      - PROM_PASS_FILE=/run/secrets/prometheus_password
    depends_on:
      - app
    networks:
      - trancendence-network
    secrets:
      - prometheus_password

  app:
    build: ./app
    container_name: 'app'
    restart: always
    environment:
      - SMTP_USER=${SMTP_USER}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/google_client_secret
      - GITHUB_CLIENT_SECRET_FILE=/run/secrets/github_client_secret
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    secrets:
      - smtp_password
      - google_client_secret
      - github_client_secret
      - jwt_secret
    networks:
      - trancendence-network
    # develop:
    #   watch:

  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: 'prometheus'
    user: root
    restart: always
    volumes:
      - ${PROMETHEUS_YML}:/etc/prometheus/prometheus.yml
      - ${RULES_YML}:/etc/prometheus/alert_rules.yml
    networks:
      - trancendence-network
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.route-prefix=/
      - --web.external-url=http://localhost/prometheus

  grafana:
    image: grafana/grafana
    container_name: 'grafana'
    networks:
      - trancendence-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ${GRAFANA_PROVISION}:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${USER_NAME}
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password
      - GF_SERVER_ROOT_URL=https://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    secrets:
      - admin_password
    depends_on:
      - prometheus

  alertmanager:
    build: 
      context: ./monitoring/alertmanager
      args:
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASS_FILE=/run/secrets/smtp_password
        - EMAIL_FROM=${SMTP_USER}
        - EMAIL_TO=${EMAIL_TO}
      secrets:
        - smtp_password
    container_name: 'alertmanager'
    restart: always
    user: root

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: 'node-exporter'
    restart: always
    command: 
      - "--path.rootfs=/host"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)"
    pid: host
    volumes:
      - /:/host:ro,rslave
    depends_on:
      - prometheus
    networks:
      - trancendence-network
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - prometheus
    networks:
      - trancendence-network
    privileged: true

secrets:
  admin_password:
    file: ${SECRETS_DIR}/grafana.txt
  prometheus_password:
    file: ${SECRETS_DIR}/prometheus.txt
  smtp_password:
    file: ${SECRETS_DIR}/smtp.txt
  google_client_secret:
    file: ${SECRETS_DIR}/google.txt
  github_client_secret:
    file: ${SECRETS_DIR}/github.txt
  jwt_secret:
    file: ${SECRETS_DIR}/jwt.txt

networks:
  trancendence-network:
    driver: bridge

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: "${GRAFANA_DATA_DIR}"
      o: bind
    