groups:
- name: transcendence
  rules:
  #Node Exporter alerts
  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"} / node_filesystem_size_bytes < .10 and on (instance, device, mountpoint) node_filesystem_readonly == 0)
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host out of disk space {{ $labels.instance }} ({{ $labels.mountpoint }})
      description: "Disk is almost full (< 10% left) on device {{ $labels.device }}\n"

  - alert: HostOutOfMemory
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < .10)
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host out of memory {{ $labels.instance }}
      description: "Node memory is filling up (< 10% left)\n"

  #cAdvisor alerts
  - alert: Container down
    expr: time() - container_last_seen > 60
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Container down - {{ $labels.name }}
      description: The container {{ $labels.name }} (image {{ $labels.image }}) is down.


