global:
  resolve_timeout: 5m

route:
  receiver: 'email'
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'email'
  email_configs:
  - smarthost: 'SMTP_HOST'
    auth_username: 'SMTP_USER'
    auth_identity: 'SMTP_USER'
    auth_password: 'SMTP_PASS'
    from: 'EMAIL_FROM'
    to: 'EMAIL_TO'
    send_resolved: true
    headers:
      subject: 'Prometheus Mail Alerts'